### ISSUE TITLE
HW 1 Errors

### ISSUE THREAD

**Issue by NicholasAsirvadam** [Lillyrives/IDS2024S#2]
Hello, the following are errors I have found in your first homework assignment:
1. The link you have included to the course webpage does not work.
2. Your links to the quiz and exam folders do not work.
3. You have not answered question 4.
4. You have not answered question 5.

Since this is the first assignment, you have the opportunity to earn some points back on these mistakes if you resolve these issues by the start of class on Monday.

**Comment by Lillyrives** [comment]
Is it possible if I can get it done today that it can count? I just had a lot of work today this week.

Sorry for the inconvenient.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NicholasAsirvadam** [comment]
Sorry, it is too late to earn points back now.

-Nicholas Asirvadam

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
